[package]
name = "liberty-parse"
description = "Liberty file format parser"
version = "0.4.1"
authors = ["Erik Ronshagen <eronshagen@gmail.com>"]
edition = "2021"
repository = "https://github.com/shages/liberty-parse"
readme = "README.md"
license = "MIT"

[badges]
azure-devops = { project = "eronshagen/shages", pipeline = "shages.liberty-parse" }

[dependencies]
nom = "5.1.2"
itertools = "0.8"
float-pretty-print = "0.1"
indexmap = "1.9.2"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "bench"
harness = false
