[package]
name = "liberty-parse"
version = "0.1.0"
authors = ["Erik Ronshagen <eronshagen@gmail.com>"]
edition = "2018"

[dependencies]
nom = "5.0.0"
itertools = "0.8.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "bench"
harness = false
